### ISSUE TITLE
Circular References

### ISSUE THREAD

**Issue by andymans** [vobyjs/oby#4]
Just an FYI - I'm seeing a (!) Circular dependencies warning when using this lib, mainly around "context.js" by the look of it.

Nice work, though!

**Comment by fabiospampinato** [comment]
Do you have anything that I can use to reproduce the problem?

**Comment by andymans** [comment]
OK - just checked again with babel set up as babel() versus babel ({exclude:...}). But the warning still appears. 

Not the build still runs ok - it's just a warning. But circular deps are always good to get rid of if poss :-)

**Comment by andymans** [comment]
I'm closing this. I've done some research, and it seems to be a well-known rollup issue.
